/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface QwExample {
        "message": string;
    }
}
declare global {
    interface HTMLQwExampleElement extends Components.QwExample, HTMLStencilElement {
    }
    var HTMLQwExampleElement: {
        prototype: HTMLQwExampleElement;
        new (): HTMLQwExampleElement;
    };
    interface HTMLElementTagNameMap {
        "qw-example": HTMLQwExampleElement;
    }
}
declare namespace LocalJSX {
    interface QwExample {
        "message"?: string;
    }
    interface IntrinsicElements {
        "qw-example": QwExample;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "qw-example": LocalJSX.QwExample & JSXBase.HTMLAttributes<HTMLQwExampleElement>;
        }
    }
}
